version: "3.8"
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=crispi
      # MONGO_INITDB_ROOT_USERNAME: crispi
      # MONGO_INITDB_ROOT_PASSWORD: pinguino
    env_file: 
      - ./env/mongo.env

  backend:
    build: ./backend
    container_name: back-multi
    #build:
    #    context: ./backend
    #    dockerfile: Dockerfile
    #    args:
    #      some-arg: hei
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app #relative path
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: front-multi
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src #relative path
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: